### ISSUE TITLE
Pyrogram issue on ubuntu 22.04

### ISSUE THREAD

**Issue by samucamg** [kjeymax/GDUPLOAD_BOT2#14]
Anything is ok, I'm using .env but I got this error.
All requirements are installed without any problem or issue

 python3 -m bot
2023-04-29 20:16:31,917 - __main__ - INFO - Starting Bot !
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/GD/bot/__main__.py", line 35, in <module>
    app.run()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/run.p                         y", line 61, in run
    self.start()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 51, in a                         sync_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_comp                         lete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/start                         .py", line 53, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/auth/connect.py                         ", line 38, in connect
    self.load_config()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/client.py", line 613, i                         n load_config
    raise AttributeError("No API Key found. More info: https://docs.pyrogram.org                         /intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/set                         up

**Comment by RaviRCoder** [comment]
Try this `pip3 install -U pyrogram tgcrypto`
otherwise this `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip`
